User story styling
anotherMichaelMaier/capstone-project pull request #21
Opened 2023-02-15 20:50 UTC by anotherMichaelMaier

2023-02-16 10:23 UTC, shebtastic requested changes
great work!

i would like to see changes to the accessibility issues and some improvements to component naming.
i would also recommend moving shared styled components to their own files and maybe look for reusable variants, which you already started to do on some parts.

2023-02-16 10:23 UTC, shebtastic commented on components/AddCard.js
> +import AddTask from "@/public/icons/addTask.svg";
when importing svg as components, they don't have to be in the `public` folder.
the `public` folder is usually reserved for static content.

2023-02-16 10:23 UTC, shebtastic commented on components/AddCard.js
> +              pattern="^[a-zA-Z0-9äüöÄÜÖ][a-zA-Z0-9-_ äüöÄÜÖ.]{1,70}"
it's a bit confusing, that the `maxLength` differs from what the `pattern` validates, even though this should work.

if the `maxLength` were to change to something *> 70*, this would cause an issue.

2023-02-16 10:23 UTC, shebtastic commented on components/Modal.js
> +// import React, { useEffect, useState } from "react";
if you don't need this, you should probably just remove it. 😁

2023-02-16 10:23 UTC, shebtastic commented on components/Card.js
> +          />
the `ModalEditCard` could probably be refactored to something smaller like

```js
<ModalEditCard
  name={name}
  note={note}
  time={time}
  tasks={tasks}
  updateTask={updateTask}
  handleClose={() => setShowModalEdit(false)}
  showModalEdit={showModalEdit}
/>
```

within the component, you're not actually using `setTasks`, while `updateTask` is what actually does the updating.
if you also want to get rid of the `id` prop, you would have to write a callback like:

```js
  updateTask={(newTask) => updateTask(id, newTask)}
```

2023-02-16 10:23 UTC, shebtastic commented on components/Card.js
> +`;
i feel like this name might be lying

2023-02-16 10:23 UTC, shebtastic commented on components/AddCard.js
>  `;
some of your styled components seem to have similar or identical counterparts. if you plan on reusing them more in the future, you should consider refactoring them out into their own component file(s).

2023-02-16 10:23 UTC, shebtastic commented on components/Card.js
> +        <DeleteTask />
for accessibility reasons, you should consider to have text along side the icon or provide at least provide an `aria-label` on the element

2023-02-16 10:23 UTC, shebtastic commented on pages/_app.js
> +      </StyledHeadline>
for headlines providing text or label is especially true, since they are landmarks.

2023-02-16 10:23 UTC, shebtastic commented on components/Card.js
> +              <StyledP>{note}</StyledP>
this kind of styled component names is highly confusing.

i would much more care about _"what is the component used for?"_ than _"what is the html tag of this component?"_.
usually you would trust the author of the component to have chosen the correct semantic tags.

2023-02-16 10:23 UTC, shebtastic commented on components/Card.js
> +  font-size: medium;
`font-size: medium;` should already be the initial value

2023-02-16 10:23 UTC, shebtastic commented on components/Card.js
> +`;
`StyledDetailsButton` might be a variant of `StyledButton`

2023-02-16 10:32 UTC, anotherMichaelMaier commented
Thanks for your feedback Michael! I'll look into those issues and refactor some of my code again. Highly appreciate your feedback.

2023-02-28 13:02 UTC, anotherMichaelMaier commented
Actually implemented all suggested changes, believe it or not.

2023-02-28 13:03 UTC, merged